services:
  # Main application service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sallma
    ports:
      - "${APP_PORT:-3001}:3001"
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    env_file:
      - .env
    profiles:
      - app
    
  # Test runner service
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sallma-dev
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    env_file:
      - .env
    working_dir: /app
    command: tail -f /dev/null
    profiles:
      - dev

volumes:
  maven_cache:

